name: movie-env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backports=1.0
  - ca-certificates=2020.10.14
  - cffi=1.14.0
  - click-didyoumean=0.0.3
  - click-repl=0.1.6
  - cryptography=3.3.1
  - flask=1.1.2
  - future=0.18.2
  - itsdangerous=1.1.0
  - libcxx=13.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libzlib=1.2.11
  - ncurses=6.2
  - openssl=1.1.1i
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - pycparser=2.20
  - pygments=2.7.4
  - python=3.8.2
  - python_abi=3.8
  - pytz=2020.5
  - readline=8.0
  - setuptools=46.1.3
  - six=1.16.0
  - sqlite=3.31.1
  - tk=8.6.8
  - wcwidth=0.2.5
  - werkzeug=1.0.1
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - python-graphviz==0.19.1
  - pip==22.1.2
  - pip:
    - aiohttp==3.8.1
    - aioredis==2.0.1
    - aiosignal==1.2.0
    - alembic==1.7.5
    - amqp==5.0.6
    - aniso8601==9.0.0
    - anyio==3.6.1
    - apispec==4.3.0
    - appnope==0.1.2
    - apscheduler==3.9.1
    - argh==0.26.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.0.5
    - async-timeout==4.0.2
    - asyncio==3.4.3
    - attrs==20.3.0
    - autopep8==1.6.0
    - babel==2.10.1
    - backcall==0.2.0
    - backports-functools-lru-cache==1.6.1
    - backports-zoneinfo==0.2.1
    - bcrypt==3.1.7
    - beautifulsoup4==4.11.1
    - billiard==3.6.4.0
    - black==22.6.0
    - bleach==5.0.0
    - blinker==1.4
    - boto3==1.16.15
    - botocore==1.19.15
    - brotli==1.0.9
    - cachetools==5.0.0
    - celery==5.1.0
    - certifi==2020.12.5
    - cfgv==3.3.1
    - chardet==3.0.4
    - charset-normalizer==2.0.12
    - cleo==1.0.0a4
    - click==7.1.2
    - click-plugins==1.1.1
    - configargparse==1.4
    - crashtest==0.3.1
    - cycler==0.11.0
    - dacite==1.6.0
    - debugpy==1.6.0
    - decorator==5.0.5
    - defusedxml==0.7.1
    - deprecated==1.2.13
    - diagrams==0.21.1
    - distlib==0.3.4
    - dnspython==2.2.1
    - email-validator==1.1.3
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - executing==0.8.3
    - fabric==2.6.0
    - factory-boy==3.2.0
    - faker==13.3.4
    - fastjsonschema==2.15.3
    - filelock==3.7.1
    - flake8==4.0.1
    - flasgger==0.9.5
    - flask-admin==1.5.7
    - flask-apispec==0.11.0
    - flask-apscheduler==1.12.2
    - flask-basicauth==0.2.0
    - flask-bcrypt==0.7.1
    - flask-celeryext==0.4.3
    - flask-cors==3.0.8
    - flask-expects-json==1.5.0
    - flask-injector==0.12.3
    - flask-jwt-extended==4.0.2
    - flask-login==0.6.0
    - flask-mail==0.9.1
    - flask-marshmallow==0.14.0
    - flask-migrate==2.5.3
    - flask-principal==0.4.0
    - flask-pydantic==0.9.0
    - flask-restful==0.3.8
    - flask-restful-swagger==0.20.2
    - flask-security-too==4.1.4
    - flask-shell-ipython==0.4.1
    - flask-sqlalchemy==2.4.4
    - flask-sse==1.0.0
    - flask-wtf==1.0.1
    - flower==1.0.0
    - fonttools==4.33.3
    - frozenlist==1.3.0
    - gevent==21.1.2
    - geventhttpclient==1.4.4
    - google-auth==2.6.0
    - greenlet==1.0.0
    - gunicorn==20.1.0
    - hiredis==2.0.0
    - humanize==4.0.0
    - identify==2.5.1
    - idna==2.10
    - importlib-metadata==4.11.3
    - importlib-resources==5.7.1
    - iniconfig==1.1.1
    - injector==0.18.4
    - invoke==1.7.0
    - ipykernel==6.13.0
    - ipython==7.23.1
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==2.11.1
    - jmespath==0.10.0
    - json5==0.9.8
    - jsonschema==3.2.0
    - jupyter-client==7.3.1
    - jupyter-core==4.10.0
    - jupyter-server==1.17.0
    - jupyterlab==3.4.2
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.14.0
    - kiwisolver==1.4.2
    - kombu==5.1.0
    - locust==1.4.3
    - mako==1.1.3
    - markupsafe==2.0.0
    - marshmallow==3.14.0
    - marshmallow-enum==1.5.1
    - marshmallow-sqlalchemy==0.26.1
    - matplotlib==3.5.2
    - matplotlib-inline==0.1.3
    - mccabe==0.6.1
    - mistune==0.8.4
    - more-itertools==8.6.0
    - msgpack==1.0.2
    - multidict==6.0.2
    - mypy==0.931
    - mypy-extensions==0.4.3
    - nbclassic==0.3.7
    - nbclient==0.6.3
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - newrelic==7.2.4.171
    - nodeenv==1.7.0
    - notebook==6.4.11
    - notebook-shim==0.1.0
    - numpy==1.22.3
    - openpyxl==3.0.9
    - packaging==20.4
    - pandas==1.4.2
    - pandocfilters==1.5.0
    - paramiko==2.10.3
    - parso==0.8.2
    - passlib==1.7.4
    - pathlib2==2.3.7.post1
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.1.1
    - pip==22.1.2
    - platformdirs==2.5.2
    - pluggy==0.13.1
    - pptree==3.1
    - pre-commit==2.19.0
    - prometheus-client==0.14.1
    - psutil==5.8.0
    - psycopg2-binary==2.8.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py==1.9.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.8.0
    - pydantic==1.9.0
    - pyflakes==2.4.0
    - pyjwt==2.0.1
    - pylev==1.4.0
    - pynacl==1.5.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pytest==5.4.2
    - pytest-ordering==0.6
    - pytest-timeout==2.0.1
    - python-dateutil==2.8.2
    - python-dotenv==0.19.1
    - python-editor==1.0.4
    - python-graphviz==0.19.1
    - python-ulid==1.1.0
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==6.0
    - pyzmq==22.3.0
    - redis==3.5.3
    - redis-om==0.0.23
    - requests==2.24.0
    - roundrobin==0.0.2
    - rsa==4.8
    - s3transfer==0.3.3
    - send2trash==1.8.0
    - sentry-sdk==1.5.6
    - slack-bolt==1.13.0
    - slack-sdk==3.15.2
    - sniffio==1.2.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.3.24
    - sqlalchemy-utils==0.37.8
    - stack-data==0.2.0
    - stripe==2.67.0
    - terminado==0.15.0
    - timeago==1.0.15
    - tinycss2==1.1.1
    - toml==0.10.1
    - tomli==2.0.1
    - tornado==6.1
    - traitlets==5.1.0
    - types-redis==4.1.21
    - types-six==1.16.15
    - typing-extensions==4.2.0
    - tzdata==2022.1
    - tzlocal==4.2
    - urllib3==1.25.11
    - vine==5.0.0
    - virtualenv==20.15.0
    - watchdog==0.9.0
    - webargs==7.0.1
    - webencodings==0.5.1
    - websocket==0.2.1
    - websocket-client==1.3.2
    - websockets==10.2
    - wrapt==1.14.0
    - wtforms==2.3.3
    - yarl==1.7.2
    - zipp==3.8.0
    - zope-event==4.5.0
    - zope-interface==5.3.0
